# Schema for the configuration files of the Custom Controller Task Module module.
controller_task.settings:
  type: config_object
  label: 'Custom Controller Task Module settings'
  mapping:
    example:
      type: string
      label: 'Example'
