# Schema for the configuration files of the CUstom Email Task Module module.
custom_email_task.settings:
  type: config_object
  label: 'CUstom Email Task Module settings'
  mapping:
    example:
      type: string
      label: 'Example'
