<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * implements hook_form_alter().
 */

/**
 * function sathyam_prakaash_form_alter(&$form, FormStateInterface $form_state, $form_id) {
 * $route = \Drupal::routematch()->getRouteName();
 * print_r($route);
 * exit;
 * }
*/

/**
  * function sathyam_prakaash_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  * if($form_id == "node_page_form" || $form_id == "node_page_edit_form")
  * { $config_service = \Drupal::service('sathyam_prakaash.config_service');
  *  $data = $config_service->getConfigFormName();
  *  print_r($data);
  *  exit;
  * }
  * }
*/
