<?php

/**
 * @file
 * Contains hook functions.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\sathyam_prakaash\Event\UserLoginEvent;

/**
 * Implements hook_form_alter().
 */
function sathyam_prakaash_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  {if($form_id == "node_page_form" || $form_id == "node_page_edit_form"){
    //print_r($form['field_genre']);
    //exit;
    $form['title']['widget'][0]['value']['#default_value'] = "Movie Name";
    //unset($form['field_genre']);
    //unset($form['field_genre']['widget']['#options']['Action']);
    $form['field_genre']['widget']['#title'] = "Movie Genre";
    $form['field_genre']['widget']['#default_value'] = ["Romance"];
    $form['field_description']['widget']['#title'] = "Movie Review";
}
}

/**
 * Implements hook_user_login().
 */
function sathyam_prakaash_user_login($account) {
  // Instantiate our event.
  $event = new UserLoginEvent($account);
  // Triggering the event_dispatcher service and dispatch the event.
  $event_dispatcher = \Drupal::service('event_dispatcher');
  $event_dispatcher->dispatch($event, UserLoginEvent::EVENT_NAME);
}

/**
 * Implements hook_theme().
 */

function sathyam_prakaash_theme($existing, $type, $theme, $path) {
  return [
    'sp_template2' => [
        'variables' => ['text' => ""],
    ],
];
}